# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0003_auto_20170222_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='feedBack',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
