# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0004_auto_20170222_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily', models.CharField(max_length=500)),
                ('sunday', models.CharField(max_length=500)),
                ('monday', models.CharField(max_length=500)),
                ('tuesday', models.CharField(max_length=500)),
                ('wednesday', models.CharField(max_length=500)),
                ('thrusday', models.CharField(max_length=500)),
                ('friday', models.CharField(max_length=500)),
                ('saturday', models.CharField(max_length=500)),
                ('typeOf', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily', models.CharField(max_length=500)),
                ('sunday', models.CharField(max_length=500)),
                ('monday', models.CharField(max_length=500)),
                ('tuesday', models.CharField(max_length=500)),
                ('wednesday', models.CharField(max_length=500)),
                ('thrusday', models.CharField(max_length=500)),
                ('friday', models.CharField(max_length=500)),
                ('saturday', models.CharField(max_length=500)),
                ('typeOf', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily', models.CharField(max_length=500)),
                ('sunday', models.CharField(max_length=500)),
                ('monday', models.CharField(max_length=500)),
                ('tuesday', models.CharField(max_length=500)),
                ('wednesday', models.CharField(max_length=500)),
                ('thrusday', models.CharField(max_length=500)),
                ('friday', models.CharField(max_length=500)),
                ('saturday', models.CharField(max_length=500)),
                ('typeOf', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
