# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0006_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='feedBack',
            field=models.CharField(max_length=99999),
        ),
    ]
