# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0007_auto_20170227_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbac', models.CharField(max_length=99999)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='feedBack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mess.Feedback'),
        ),
    ]
