# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0008_auto_20170228_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedbac',
        ),
        migrations.RemoveField(
            model_name='student',
            name='feedBack',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mess.Student'),
        ),
    ]
