# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0010_auto_20170228_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='feedBack',
        ),
        migrations.AddField(
            model_name='feedback',
            name='stu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mess.Student'),
        ),
    ]
