# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0012_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=1000, null=True)),
                ('amount', models.IntegerField()),
                ('stud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mess.Student')),
            ],
        ),
    ]
