# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0013_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
